In [1]:
pip install pandas sqlalchemy psycopg python-dotenv

Requirement already satisfied: pandas in /home/bruno/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in /home/bruno/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: psycopg in /home/bruno/anaconda3/lib/python3.13/site-packages (3.3.3)
Requirement already satisfied: python-dotenv in /home/bruno/anaconda3/lib/python3.13/site-packages (1.1.0)
Requirement already satisfied: numpy>=1.26.0 in /home/bruno/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/bruno/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/bruno/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/bruno/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in /home/bruno/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/bruno/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /home/bruno/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
colunas = [
    'document_id', 'paciente_idade', 'paciente_dataNascimento', 'paciente_enumSexoBiologico', 'paciente_racaCor_valor',
    'estabelecimento_razaoSocial', 'estalecimento_noFantasia', 'estabelecimento_municipio_codigo', 
    'estabelecimento_municipio_nome', 'vacina_grupoAtendimento_codigo', 'vacina_grupoAtendimento_nome', 
    'vacina_categoria_codigo','vacina_categoria_nome', 'vacina_fabricante_nome', 
    'vacina_dataAplicacao','vacina_descricao_dose', 'vacina_codigo', 'vacina_nome'
]

In [4]:
dados_vacinas = pd.read_csv('../DadosVacinação/DadosVacinaçãoRS.csv', sep=';', usecols=colunas)

In [5]:
new_names = { 
             'paciente_idade': 'idade', 
             'paciente_dataNascimento': 'data_nascimento', 
             'paciente_enumSexoBiologico': 'sexo', 
             'paciente_racaCor_valor': 'raca',
             'estabelecimento_razaoSocial': 'razao_social', 
             'estalecimento_noFantasia': 'nome_fantasia', 
             'estabelecimento_municipio_codigo': 'codigo_municipio', 
             'estabelecimento_municipio_nome': 'nome_municipio',
             'vacina_grupoAtendimento_codigo': 'codigo_grupo', 
             'vacina_grupoAtendimento_nome': 'nome_grupo', 
             'vacina_categoria_codigo': 'codigo_categoria',
             'vacina_categoria_nome': 'nome_categoria', 
             'vacina_fabricante_nome': 'fabricante_vacina', 
             'vacina_dataAplicacao': 'data_aplicacao',
             'vacina_descricao_dose': 'dose', 
             'vacina_codigo': 'codigo_vacina', 
             'vacina_nome': 'nome_vacina'
            }

dados_vacinas = dados_vacinas.rename(columns=new_names)

In [6]:
print(len(dados_vacinas))
dados_vacinas.head()

6701515

,document_id,idade,data_nascimento,sexo,raca,razao_social,nome_fantasia,codigo_municipio,nome_municipio,codigo_grupo,nome_grupo,codigo_categoria,nome_categoria,fabricante_vacina,data_aplicacao,dose,codigo_vacina,nome_vacina
0,9954e2b2-84c6-4b72-a258-33356c35e0fc-i0b0,18.0,2005-02-26,F,BRANCA,MUNICIPIO DE PELOTAS,CENTRAL REDE DE FRIO MUNICIPL NUCLEO MUNCIPAL,431440,PELOTAS,210,Faixa Etária,2.0,Faixa Etária,PFIZER,2023-03-29,3ª Dose,87,COVID-19 PFIZER - COMIRNATY
1,4d82ee6a-af7d-4dc7-82e3-5e490b044ad8-i0b0,41.0,1980-08-17,F,BRANCA,MUNICIPIO DE PELOTAS,CENTRAL REDE DE FRIO MUNICIPL NUCLEO MUNCIPAL,431440,PELOTAS,926,Outros,9.0,Trabalhadores de Saúde,PFIZER,2021-11-12,Reforço,87,COVID-19 PFIZER - COMIRNATY
2,99555ebb-09be-49c9-adee-6c5e5cd74b51-i0b0,23.0,1998-08-22,F,BRANCA,PREFEITURA MUNICIPAL DE PASSO DO SOBRADO,POSTO DE SAUDE,431407,PASSO DO SOBRADO,201,Pessoas de 18 a 64 anos,2.0,Faixa Etária,PFIZER,2021-10-19,2ª Dose,87,COVID-19 PFIZER - COMIRNATY
3,4d82fc50-15d9-457e-807d-fe367c5b1bbf-i0b0,48.0,1973-11-25,F,BRANCA,PREFEITURA MUNICIPAL DE BARRA DO RIBEIRO,ESF TRES VENDAS,430190,BARRA DO RIBEIRO,103,Diabetes Mellitus,1.0,Comorbidades,ASTRAZENECA/FIOCRUZ,2022-07-15,2º Reforço,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD
4,995884d2-ad32-452b-b599-c49c0348aebf-i0b0,37.0,1985-09-07,F,BRANCA,PREFEITURA MUNICIPAL DE VERA CRUZ,ESTRATEGIA SAUDE DA FAMILIA DE LINHA HENRIQUE ...,432270,VERA CRUZ,201,Pessoas de 18 a 64 anos,2.0,Faixa Etária,JANSSEN,2022-11-22,3º Reforço,88,COVID-19 JANSSEN - Ad26.COV2.S

In [7]:
print('Dados nulos:')
print(dados_vacinas.isna().sum())

Dados nulos:
document_id               0
idade                    10
data_nascimento          10
sexo                     10
raca                     11
razao_social              0
nome_fantasia             0
codigo_municipio          0
nome_municipio            0
codigo_grupo              0
nome_grupo            31940
codigo_categoria     262076
nome_categoria       262076
fabricante_vacina         0
data_aplicacao            0
dose                     64
codigo_vacina             0
nome_vacina             192
dtype: int64

In [10]:
# Tratamento de colunas None, Null, NaN

dados_vacinas['sexo'] = dados_vacinas['sexo'].fillna('Não informado')
dados_vacinas['raca'] = dados_vacinas['raca'].fillna('Não informado')
dados_vacinas['nome_grupo'] = dados_vacinas['nome_grupo'].fillna('Desconhecido')
dados_vacinas['codigo_categoria'] = dados_vacinas['codigo_categoria'].fillna(99999)
dados_vacinas['nome_categoria'] = dados_vacinas['nome_categoria'].fillna('Desconhecida')
dados_vacinas['dose'] = dados_vacinas['dose'].fillna('Desconhecida')
dados_vacinas['nome_vacina'] = dados_vacinas['nome_vacina'].fillna('Desconhecida')

In [13]:
print('Dados nulos:')
print(dados_vacinas.isna().sum())

# Idade será salva como Null e data_nascimento como NaT

Dados nulos:
document_id            0
idade                 10
data_nascimento      368
sexo                   0
raca                   0
razao_social           0
nome_fantasia          0
codigo_municipio       0
nome_municipio         0
codigo_grupo           0
nome_grupo             0
codigo_categoria       0
nome_categoria         0
fabricante_vacina      0
data_aplicacao         0
dose                   0
codigo_vacina          0
nome_vacina            0
dtype: int64

In [14]:
# Converter colunas datas para date
dados_vacinas['data_aplicacao'] = pd.to_datetime(dados_vacinas['data_aplicacao'], format='%Y-%m-%d', errors='coerce')
dados_vacinas['data_nascimento'] = pd.to_datetime(dados_vacinas['data_nascimento'], format='%Y-%m-%d', errors='coerce')

In [15]:
# Função de limpeza e padronização
import unicodedata
import re

def limpeza(texto):
    if not isinstance(texto, str):
        return texto
    
    # remover espaços no início e fim
    texto = texto.strip()
    
    # converter para minúsculo
    texto = texto.lower()
    
    # remover acentos
    texto = unicodedata.normalize('NFKD', texto).encode('ASCII', 'ignore').decode('ASCII')
    
    # remover caracteres especiais (mantém letras, números e espaço)
    texto = re.sub(r'[^a-z0-9\s]', '', texto)
    
    # remover múltiplos espaços
    texto = re.sub(r'\s+', ' ', texto)
    
    return texto

In [16]:
for col in dados_vacinas.select_dtypes(include="object"):
    dados_vacinas[col] = dados_vacinas[col].apply(limpeza)

In [17]:
print('Limpeza concluída')
dados_vacinas.head()

Limpeza concluída

,document_id,idade,data_nascimento,sexo,raca,razao_social,nome_fantasia,codigo_municipio,nome_municipio,codigo_grupo,nome_grupo,codigo_categoria,nome_categoria,fabricante_vacina,data_aplicacao,dose,codigo_vacina,nome_vacina
0,9954e2b284c64b72a25833356c35e0fci0b0,18.0,2005-02-26,f,branca,municipio de pelotas,central rede de frio municipl nucleo muncipal,431440,pelotas,210,faixa etaria,2.0,faixa etaria,pfizer,2023-03-29,3a dose,87,covid19 pfizer comirnaty
1,4d82ee6aaf7d4dc782e35e490b044ad8i0b0,41.0,1980-08-17,f,branca,municipio de pelotas,central rede de frio municipl nucleo muncipal,431440,pelotas,926,outros,9.0,trabalhadores de saude,pfizer,2021-11-12,reforco,87,covid19 pfizer comirnaty
2,99555ebb09be49c9adee6c5e5cd74b51i0b0,23.0,1998-08-22,f,branca,prefeitura municipal de passo do sobrado,posto de saude,431407,passo do sobrado,201,pessoas de 18 a 64 anos,2.0,faixa etaria,pfizer,2021-10-19,2a dose,87,covid19 pfizer comirnaty
3,4d82fc5015d9457e807dfe367c5b1bbfi0b0,48.0,1973-11-25,f,branca,prefeitura municipal de barra do ribeiro,esf tres vendas,430190,barra do ribeiro,103,diabetes mellitus,1.0,comorbidades,astrazenecafiocruz,2022-07-15,2o reforco,85,covid19 astrazenecafiocruz covishield
4,995884d2ad32452bb599c49c0348aebfi0b0,37.0,1985-09-07,f,branca,prefeitura municipal de vera cruz,estrategia saude da familia de linha henrique ...,432270,vera cruz,201,pessoas de 18 a 64 anos,2.0,faixa etaria,janssen,2022-11-22,3o reforco,88,covid19 janssen ad26cov2s

In [18]:
# DIM PACIENTE

colunas_paciente = ['document_id', 'idade', 'data_nascimento', 'sexo', 'raca']

dim_paciente = dados_vacinas[colunas_paciente].drop_duplicates(subset='document_id').reset_index(drop=True)
dim_paciente['id_paciente'] = dim_paciente.index + 1

# Reorganizar as colunas
dim_paciente = dim_paciente[['id_paciente', 'document_id', 'idade', 'data_nascimento', 'sexo', 'raca']]

print('dim paciente criada com sucesso')
print('Pacientes: ', len(dim_paciente))

# Deve retornar TRUE isso garante que cada ID é único
print(dim_paciente['document_id'].is_unique)
dim_paciente.head()

dim paciente criada com sucesso
Pacientes:  6701515
True

,id_paciente,document_id,idade,data_nascimento,sexo,raca
0,1,9954e2b284c64b72a25833356c35e0fci0b0,18.0,2005-02-26,f,branca
1,2,4d82ee6aaf7d4dc782e35e490b044ad8i0b0,41.0,1980-08-17,f,branca
2,3,99555ebb09be49c9adee6c5e5cd74b51i0b0,23.0,1998-08-22,f,branca
3,4,4d82fc5015d9457e807dfe367c5b1bbfi0b0,48.0,1973-11-25,f,branca
4,5,995884d2ad32452bb599c49c0348aebfi0b0,37.0,1985-09-07,f,branca

In [19]:
# DIM GRUPO_ATENDIMENTO

colunas_grupo_atendimento = ['nome_grupo', 'codigo_grupo']

dim_grupo_atendimento = (dados_vacinas[colunas_grupo_atendimento]
    .drop_duplicates(subset='codigo_grupo')
    .reset_index(drop=True))
dim_grupo_atendimento['id_grupo_atendimento'] = dim_grupo_atendimento.index + 1

# Reorganizar as colunas
dim_grupo_atendimento = dim_grupo_atendimento[['id_grupo_atendimento', 'codigo_grupo', 'nome_grupo']]

print('dim grupo_atendimento criada com sucesso')
print('Grupos de Atendimento: ', len(dim_grupo_atendimento))

# Deve retornar TRUE isso garante que cada ID é único
print(dim_grupo_atendimento['codigo_grupo'].is_unique)
dim_grupo_atendimento.head()

dim grupo_atendimento criada com sucesso
Grupos de Atendimento:  102
True

   id_grupo_atendimento  codigo_grupo               nome_grupo
0                     1           210             faixa etaria
1                     2           926                   outros
2                     3           201  pessoas de 18 a 64 anos
3                     4           103        diabetes mellitus
4                     5           203  pessoas de 70 a 74 anos

In [20]:
# DIM CATEGORIA

colunas_categoria = ['codigo_categoria','nome_categoria']

dim_categoria = dados_vacinas[colunas_categoria].drop_duplicates(subset='codigo_categoria').reset_index(drop=True)
dim_categoria['id_categoria'] = dim_categoria.index + 1

# Reorganizar as colunas
dim_categoria = dim_categoria[['id_categoria','codigo_categoria','nome_categoria']]

print('dim categoria criada com sucesso')
print('Categorias: ', len(dim_categoria))

# Deve retornar TRUE isso garante que cada ID é único
print(dim_categoria['codigo_categoria'].is_unique)
dim_categoria.head()

dim categoria criada com sucesso
Categorias:  22
True

,id_categoria,codigo_categoria,nome_categoria
0,1,2.0,faixa etaria
1,2,9.0,trabalhadores de saude
2,3,1.0,comorbidades
3,4,3.0,pessoas de 60 anos ou mais institucionalizadas
4,5,25.0,puerperas

In [21]:
# DIM LOCALIDADE

colunas_localidade = ['codigo_municipio','nome_municipio']

dim_localidade = dados_vacinas[colunas_localidade].drop_duplicates(subset='codigo_municipio').reset_index(drop=True)
dim_localidade['id_localidade'] = dim_localidade.index + 1

# Reorganizar as colunas
dim_localidade = dim_localidade[['id_localidade','codigo_municipio','nome_municipio']]

print('dim localidade criada com sucesso')
print('Localidades: ', len(dim_categoria))

# Deve retornar TRUE isso garante que cada ID é único
print(dim_localidade['codigo_municipio'].is_unique)
dim_localidade.head()

dim localidade criada com sucesso
Localidades:  22
True

   id_localidade  codigo_municipio    nome_municipio
0              1            431440           pelotas
1              2            431407  passo do sobrado
2              3            430190  barra do ribeiro
3              4            432270         vera cruz
4              5            430510     caxias do sul

In [22]:
# DIM ESTABELECIMENTO

colunas_estabelecimento = ['razao_social','nome_fantasia']

dim_estabelecimento = dados_vacinas[colunas_estabelecimento].drop_duplicates().reset_index(drop=True)
dim_estabelecimento['id_estabelecimento'] = dim_estabelecimento.index + 1

# Reorganiza as colunas
dim_estabelecimento = dim_estabelecimento[['id_estabelecimento', 'razao_social','nome_fantasia']]

print('dim estabelecimento criada com sucesso')
print('Estabelecimentos: ', len(dim_estabelecimento))

# Deve retornar TRUE isso garante que cada ID é único
print(dim_estabelecimento['id_estabelecimento'].is_unique)
dim_estabelecimento.head()

dim estabelecimento criada com sucesso
Estabelecimentos:  2513
True

,id_estabelecimento,razao_social,nome_fantasia
0,1,municipio de pelotas,central rede de frio municipl nucleo muncipal
1,2,prefeitura municipal de passo do sobrado,posto de saude
2,3,prefeitura municipal de barra do ribeiro,esf tres vendas
3,4,prefeitura municipal de vera cruz,estrategia saude da familia de linha henrique ...
4,5,prefeitura municipal de caxias do sul,ubs esplanada

In [23]:
# DIM VACINA

colunas_vacina = ['nome_vacina', 'codigo_vacina', 'fabricante_vacina']

dim_vacina = dados_vacinas[colunas_vacina].drop_duplicates(subset='codigo_vacina').reset_index(drop=True)
dim_vacina['id_vacina'] = dim_vacina.index + 1

# Reorganiza as colunas
dim_vacina = dim_vacina[['id_vacina','fabricante_vacina','codigo_vacina','nome_vacina']]

print('dim vacina criada com sucesso')
print('Vacinas: ', len(dim_vacina))

# Deve retornar TRUE isso garante que cada ID é único
print(dim_vacina['codigo_vacina'].is_unique)
dim_vacina.head()

dim vacina criada com sucesso
Vacinas:  13
True

,id_vacina,fabricante_vacina,codigo_vacina,nome_vacina
0,1,pfizer,87,covid19 pfizer comirnaty
1,2,astrazenecafiocruz,85,covid19 astrazenecafiocruz covishield
2,3,janssen,88,covid19 janssen ad26cov2s
3,4,sinovacbutantan,86,covid19 sinovacbutantan coronavac
4,5,pfizer,103,covid19 pfizer comirnaty bivalente

In [24]:
# DIM DATA

# Data mínima e máxima dos atendimentos
data_inicio = '2020-01-01'
data_fim = dados_vacinas['data_aplicacao'].max()

# Sequência contínua de dias (sem buracos)
dias_continuos = pd.date_range(start=data_inicio, end=data_fim, freq='D')

# Transforme essa sequência no seu DataFrame de Dimensão
dim_data = pd.DataFrame({'data': dias_continuos})

# Criando o id_data no formato AAAAMMDD
dim_data['id_data'] = dim_data['data'].dt.strftime('%Y%m%d').astype(int)

# Os atributos da dimensão
dim_data['ano'] = dim_data['data'].dt.year
dim_data['mes'] = dim_data['data'].dt.month
dim_data['dia'] = dim_data['data'].dt.day
dim_data['dia_semana'] = dim_data['data'].dt.day_name()
dim_data['trimestre'] = dim_data['data'].dt.quarter

# Reorganizando as colunas
dim_data = dim_data[['id_data', 'data', 'ano', 'mes', 'dia', 'dia_semana', 'trimestre']]

print(dim_data.head())

    id_data       data   ano  mes  dia dia_semana  trimestre
0  20200101 2020-01-01  2020    1    1  Wednesday          1
1  20200102 2020-01-02  2020    1    2   Thursday          1
2  20200103 2020-01-03  2020    1    3     Friday          1
3  20200104 2020-01-04  2020    1    4   Saturday          1
4  20200105 2020-01-05  2020    1    5     Sunday          1

In [25]:
# Merge com dim_paciente

df_temp = pd.merge(
    left=dados_vacinas,
    right=dim_paciente[['id_paciente', 'document_id']],
    on='document_id',
    how="left",
    validate="m:1"
)

In [26]:
print('Merge com dim_paciente concluido com sucesso')

Merge com dim_paciente concluido com sucesso

In [27]:
del dados_vacinas

In [28]:
# Merge com dim_grupo_atendimento

df_temp = pd.merge(
    left=df_temp,
    right=dim_grupo_atendimento[['id_grupo_atendimento', 'codigo_grupo']],
    on='codigo_grupo',
    how="left",
    validate="m:1"
)

In [29]:
print('Merge com dim_grupo_atendimento concluido com sucesso')

Merge com dim_grupo_atendimento concluido com sucesso

In [30]:
# Merge com dim_categoria

df_temp = pd.merge(
    left=df_temp,
    right=dim_categoria[['id_categoria', 'codigo_categoria']],
    on='codigo_categoria',
    how="left",
    validate="m:1"
)

In [31]:
print('Merge com dim_categoria concluido com sucesso')

Merge com dim_categoria concluido com sucesso

In [32]:
# Merge com dim_localidade

df_temp = pd.merge(
    left=df_temp,
    right=dim_localidade[['id_localidade', 'codigo_municipio']],
    on='codigo_municipio',
    how="left",
    validate="m:1"
)

In [33]:
print('Merge com dim_localidade concluido com sucesso')

Merge com dim_localidade concluido com sucesso

In [34]:
# Merge com dim_estabelecimento

df_temp = pd.merge(
    left=df_temp,
    right=dim_estabelecimento[['id_estabelecimento', 'razao_social','nome_fantasia']],
    on=['razao_social','nome_fantasia'],
    how="left",
    validate="m:1"
)

In [35]:
print('Merge com dim_estabelecimento concluido com sucesso')

Merge com dim_estabelecimento concluido com sucesso

In [36]:
# Merge com dim_vacina

df_temp = pd.merge(
    left=df_temp,
    right=dim_vacina[['id_vacina', 'codigo_vacina']],
    on='codigo_vacina',
    how="left",
    validate="m:1"
)

In [37]:
print('Merge com dim_vacina concluido com sucesso')

Merge com dim_vacina concluido com sucesso

In [38]:
# Converter Data para ID formato AAAAMMDD
df_temp['id_data'] = df_temp['data_aplicacao'].dt.strftime('%Y%m%d').astype(int)

df_temp = df_temp[df_temp["id_data"].isin(dim_data["id_data"])]
#df_temp = df_temp.merge(dim_data[["id_data"]], on="id_data", how="inner")

In [40]:
print('Merge com dim_data concluido com sucesso')
df_temp.head()

Merge com dim_data concluido com sucesso

,document_id,idade,data_nascimento,sexo,raca,razao_social,nome_fantasia,codigo_municipio,nome_municipio,codigo_grupo,...,dose,codigo_vacina,nome_vacina,id_paciente,id_grupo_atendimento,id_categoria,id_localidade,id_estabelecimento,id_vacina,id_data
0,9954e2b284c64b72a25833356c35e0fci0b0,18.0,2005-02-26,f,branca,municipio de pelotas,central rede de frio municipl nucleo muncipal,431440,pelotas,210,...,3a dose,87,covid19 pfizer comirnaty,1,1,1,1,1,1,20230329
1,4d82ee6aaf7d4dc782e35e490b044ad8i0b0,41.0,1980-08-17,f,branca,municipio de pelotas,central rede de frio municipl nucleo muncipal,431440,pelotas,926,...,reforco,87,covid19 pfizer comirnaty,2,2,2,1,1,1,20211112
2,99555ebb09be49c9adee6c5e5cd74b51i0b0,23.0,1998-08-22,f,branca,prefeitura municipal de passo do sobrado,posto de saude,431407,passo do sobrado,201,...,2a dose,87,covid19 pfizer comirnaty,3,3,1,2,2,1,20211019
3,4d82fc5015d9457e807dfe367c5b1bbfi0b0,48.0,1973-11-25,f,branca,prefeitura municipal de barra do ribeiro,esf tres vendas,430190,barra do ribeiro,103,...,2o reforco,85,covid19 astrazenecafiocruz covishield,4,4,3,3,3,2,20220715
4,995884d2ad32452bb599c49c0348aebfi0b0,37.0,1985-09-07,f,branca,prefeitura municipal de vera cruz,estrategia saude da familia de linha henrique ...,432270,vera cruz,201,...,3o reforco,88,covid19 janssen ad26cov2s,5,3,1,4,4,3,20221122

In [41]:
# Criação da fato_atendimento

colunas_fato_atendimento = ['id_paciente', 'dose', 'id_grupo_atendimento', 'id_categoria', 
                            'id_localidade', 'id_estabelecimento', 'id_vacina', 'id_data']

fato_atendimento = df_temp[colunas_fato_atendimento].copy().reset_index(drop=True)
fato_atendimento['id_atendimento'] = fato_atendimento.index + 1

In [42]:
print('fato_atendimento criada com sucesso')
print('Atendimentos: ', len(fato_atendimento))
fato_atendimento.head()

fato_atendimento criada com sucesso
Atendimentos:  6701508

,id_paciente,dose,id_grupo_atendimento,id_categoria,id_localidade,id_estabelecimento,id_vacina,id_data,id_atendimento
0,1,3a dose,1,1,1,1,1,20230329,1
1,2,reforco,2,2,1,1,1,20211112,2
2,3,2a dose,3,1,2,2,1,20211019,3
3,4,2o reforco,4,3,3,3,2,20220715,4
4,5,3o reforco,3,1,4,4,3,20221122,5

In [43]:
del df_temp

In [44]:
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

load_dotenv("../.env")

db_user = os.getenv("DB_USER")
db_password = os.getenv("DB_PASSWORD")
db_host = os.getenv("DB_HOST")
db_port= os.getenv("DB_PORT")
db_name = os.getenv("DB_NAME")

engine = create_engine(
    f"postgresql+psycopg2://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"
)

print('Conexão com o banco realizada com sucesso')

Conexão com o banco realizada com sucesso

In [45]:
dim_paciente.to_sql("dim_paciente", engine, if_exists="append", index=False, chunksize=1000, method="multi")

6701515

In [46]:
dim_grupo_atendimento.to_sql("dim_grupo_atendimento", engine, if_exists="append", index=False, chunksize=1000, method="multi")

102

In [47]:
dim_categoria.to_sql("dim_categoria", engine, if_exists="append", index=False, chunksize=1000, method="multi")

22

In [48]:
dim_localidade.to_sql("dim_localidade", engine, if_exists="append", index=False, chunksize=1000, method="multi")

497

In [49]:
dim_estabelecimento.to_sql("dim_estabelecimento", engine, if_exists="append", index=False, chunksize=1000, method="multi")

2513

In [50]:
dim_vacina.to_sql("dim_vacina", engine, if_exists="append", index=False, chunksize=1000, method="multi")

13

In [51]:
dim_data.to_sql("dim_data", engine, if_exists="append", index=False, chunksize=1000, method="multi")

1713

In [54]:
fato_atendimento.to_sql("fato_atendimento", engine, if_exists="append", index=False, chunksize=1000, method="multi")

6701508

In [55]:
from sqlalchemy import text

with engine.connect() as conn:
    print(conn.execute(text("SELECT COUNT(*) FROM dim_paciente")).fetchone())
    print(conn.execute(text("SELECT COUNT(*) FROM dim_grupo_atendimento")).fetchone())
    print(conn.execute(text("SELECT COUNT(*) FROM dim_data")).fetchone())
    print(conn.execute(text("SELECT COUNT(*) FROM dim_estabelecimento")).fetchone())
    print(conn.execute(text("SELECT COUNT(*) FROM dim_categoria")).fetchone())
    print(conn.execute(text("SELECT COUNT(*) FROM dim_localidade")).fetchone())
    print(conn.execute(text("SELECT COUNT(*) FROM dim_vacina")).fetchone())
    print(conn.execute(text("SELECT COUNT(*) FROM fato_atendimento")).fetchone())

(6701515,)
(102,)
(1713,)
(2513,)
(22,)
(497,)
(13,)
(6701508,)